name: routegen
description: A new Flutter Route Generator plugin to reduce errors and give compile time errors on route paramters change.
version: 0.0.1
author: Dave Parth<parth.dave93@gmail.com>
homepage: www.google.com

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  build: ^1.1.3
  source_gen: ^0.9.4+2
  route_gen_lib:
    path: ../route_gen_lib/

dev_dependencies:
  test: ^1.6.2
